# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
        migrations.AlterModelTable(
            name='emailverifyrecord',
            table='email_verify_record',
        ),
    ]
